package view;

import javax.swing.*;
import java.awt.*;

public class Home extends JFrame {
    private JPanel HomePanel;
    private JButton checkoutBookButton;
    private JButton searchMemberButton;
    private JButton searchBookButton;
    private JButton addMemberButton;
    private JButton addCopyButton;
    private JButton addBookButton;

    Home() {
        setVisible(true);
        add(HomePanel);
    }

    public static void main(String[] args) {
        EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Home();
            }
        });
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        HomePanel = new JPanel();
        HomePanel.setLayout(new GridBagLayout());
        checkoutBookButton = new JButton();
        checkoutBookButton.setText("Checkout Book");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        HomePanel.add(checkoutBookButton, gbc);
        searchMemberButton = new JButton();
        searchMemberButton.setText("Search Member");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        HomePanel.add(searchMemberButton, gbc);
        searchBookButton = new JButton();
        searchBookButton.setText("Search Book");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        HomePanel.add(searchBookButton, gbc);
        addMemberButton = new JButton();
        addMemberButton.setText("Add Member");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        HomePanel.add(addMemberButton, gbc);
        addCopyButton = new JButton();
        addCopyButton.setText("Add Copy");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        HomePanel.add(addCopyButton, gbc);
        addBookButton = new JButton();
        addBookButton.setText("Add Book");
        gbc = new GridBagConstraints();
        gbc.gridx = 2;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        HomePanel.add(addBookButton, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return HomePanel;
    }
}
